version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: pfwjs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pfwjs.rule=Host(`pfwjs.${HOST}`)"
      - traefik.http.routers.mantrae.entrypoints=websecure
      - traefik.http.routers.mantrae.tls.certresolver=cloudflare
      - "traefik.http.services.pfwjs.loadbalancer.server.url=http://pfwjs"
    networks:
      - frontend
    volumes:
      - ./atividades:/usr/share/nginx/html/atividades:ro

networks:
  frontend:
    external: true