version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: pfwjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.pfwjs.rule=Host(`pfwjs.${HOST}`)
      - traefik.http.routers.pfwjs.entrypoints=websecure
      - traefik.http.routers.pfwjs.tls.certresolver=cloudflare
    networks:
      - frontend
    volumes:
      - ./atividades:/usr/share/nginx/html/atividades:ro

networks:
  frontend:
    external: true